import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  final Map<String, String> _translations = {
    'dashboard': 'لوحة التحكم',
    'lateToday': 'المتأخرون اليوم',
    'absentToday': 'الغائبون اليوم',
    'presentToday': 'الحاضرون اليوم',
    'totalEmployees': 'إجمالي المقاتلين',
    'recentActivity': 'النشاط الأخير',
    'checkedInAt': 'سجل حضور في',
    'minutesAgo': 'دقيقة مضت',
    'am': 'صباحاً',
    'pm': 'مساءً',
    'employees': 'المقاتلين',
    'attendance': 'الدوام',
    'reports': 'التقارير',
    'settings': 'الإعدادات',
    'name': 'الاسم',
    'phone': 'رقم الهاتف',
    'department': 'القسم',
    'hireDate': 'تاريخ التعيين',
    'status': 'الحالة',
    'active': 'فعال',
    'inactive': 'غير فعال',
    'addEmployee': 'إضافة مقاتل',
    'editEmployee': 'تعديل بيانات المقاتل',
    'deleteEmployee': 'حذف المقاتل',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'confirmDelete': 'تأكيد الحذف',
    'areYouSure': 'هل أنت متأكد؟',
    'yes': 'نعم',
    'no': 'لا',
    'search': 'بحث',
    'noResults': 'لا توجد نتائج',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'تم بنجاح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'scanQR': 'مسح رمز QR',
    'generateQR': 'إنشاء رمز QR',
    'exportPDF': 'تصدير PDF',
    'exportExcel': 'تصدير Excel',
    'print': 'طباعة',
    'filter': 'تصفية',
    'sort': 'ترتيب',
    'ascending': 'تصاعدي',
    'descending': 'تنازلي',
    'today': 'اليوم',
    'yesterday': 'أمس',
    'lastWeek': 'الأسبوع الماضي',
    'lastMonth': 'الشهر الماضي',
    'custom': 'مخصص',
    'from': 'من',
    'to': 'إلى',
    'apply': 'تطبيق',
    'reset': 'إعادة تعيين',
    'close': 'إغلاق',
  };

  String translate(String key) {
    return _translations[key] ?? key;
  }

  TextDirection get textDirection => TextDirection.rtl;
} 